### ISSUE TITLE
Exe not opening

### ISSUE THREAD

**Issue by Krashercorr** [Auricrystal/RemnantBuildRandomizer#2]
Testing program on a new character and the .exe won't open at all despite trying to alter permissions and compatibility modes. Currently using Windows 7. Not sure where else to start for troubleshooting.

**Comment by Auricrystal** [comment]
Apologies for being late, have you tried the steps in [Issue #1](https://github.com/Auricrystal/RemnantBuildRandomizer/issues/1)? 
The easiest way for me to try to find the problem would be for you to zip your SaveGames folder and upload it to google drive or some other hosting website so I can download it and try to reproduce the problem.
