### ISSUE TITLE
[Idea] Add a tab for unique/rare events

### ISSUE THREAD

**Issue by dimak** [Auricrystal/RemnantBuildRandomizer#3]
Just like Bosses and Vendors, I would like to have a tab designated to the unique events. Can have Difficulty, Name, Loot Drop (if any)

**Comment by Auricrystal** [comment]
I already have a few events (Barn Siege, Magirs Dirge, Fetid Pools) but they are sprinkled into the Bosses and Vendors Tabs, I can see about adding an Events tab although it will be short until I find more events to add.

**Comment by Auricrystal** [comment]
Added in [2.13.1](https://github.com/Auricrystal/RemnantMultipurposeManager/releases/tag/2.13.1)
