### ISSUE TITLE
[Bug] Adding a Misc Save resets entered meta data

### ISSUE THREAD

**Issue by dimak** [Auricrystal/RemnantBuildRandomizer#4]
The entire misc save section is a bit buggy. If you enter extra meta data about a save, it will persist until you add a new save to the list. At that point, only the parts of the filename will remain populated.  

If just using the filename to set the fields, not all events are getting their world set correctly unless they are listed in https://github.com/Auricrystal/RemnantMultipurposeManager/blob/master/WorldSave.cs#L26-L35 and spelled exactly the same way. There does not appear to be a way to parse the difficulty from the filename without adding it as a modifier as well.

**Comment by Auricrystal** [comment]
Thanks for the report! Ill see if I can make this more stable, I do see the metadata being wiped upon adding a new save, might have to rework how the data is being stored, possibly as an actual folder system where Diff->World->Name->Modifiers.sav.

Ill work on it and should have something within the week.

**Comment by Auricrystal** [comment]
Fixed in [2.13.1](https://github.com/Auricrystal/RemnantMultipurposeManager/releases/tag/2.13.1)
